In [1]:
from pathlib import Path

import pandas as pd

root = Path.cwd()

Eg df

In [2]:
df = pd.read_csv("google/all.csv")
df.head()

,ID,URL,Title,Difficulty,Acceptance %,Frequency %
0,1,https://leetcode.com/problems/two-sum,Two Sum,Easy,57.5%,100.0%
1,2,https://leetcode.com/problems/add-two-numbers,Add Two Numbers,Medium,48.5%,75.0%
2,3,https://leetcode.com/problems/longest-substrin...,Longest Substring Without Repeating Characters,Medium,39.1%,75.0%
3,4,https://leetcode.com/problems/median-of-two-so...,Median of Two Sorted Arrays,Hard,46.6%,75.0%
4,8,https://leetcode.com/problems/string-to-intege...,String to Integer (atoi),Medium,21.0%,37.5%

Read and merge all csv files

In [3]:
df_list = []

for folder in root.iterdir():

    csv = folder / "all.csv"

    if not csv.exists():
        continue

    df = pd.read_csv(csv, usecols=['ID'])
    df['company'] = folder.name
    df_list.append(df)

combined = pd.concat(df_list, ignore_index=True)

Problem : company mapping

In [4]:
summary = (
    combined
    .groupby('ID', as_index=False)['company']
    .agg(lambda values: sorted(set(values)))
)
summary.head()

   ID                                            company
0   1  [accenture, accolite, adobe, agoda, airbnb, ai...
1   2  [accenture, accolite, adobe, airbnb, amazon, a...
2   3  [accenture, accolite, adobe, agoda, airtel, ak...
3   4  [accenture, adobe, amazon, apple, arcesium, au...
4   5  [accenture, accolite, adobe, amazon, apple, ar...

Save json

In [5]:
summary.to_json(
    root / 'problem_company_mapping.json',
    orient='records',
)

In [6]:
# summary.to_csv(
#     root / 'problem_company_mapping.csv',
#     index=False
# )